//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpubMerge.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpubMerge.Gui.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件 的本地化字符串。
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 也可以使用下方按钮添加文件 的本地化字符串。
        /// </summary>
        public static string AddFilesHint {
            get {
                return ResourceManager.GetString("AddFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者：lanut |  的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在取消合并… 的本地化字符串。
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取封面路径 的本地化字符串。
        /// </summary>
        public static string CannotReadCoverPath {
            get {
                return ResourceManager.GetString("CannotReadCoverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择封面 的本地化字符串。
        /// </summary>
        public static string ChooseCover {
            get {
                return ResourceManager.GetString("ChooseCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择位置 的本地化字符串。
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此图片暂时无法展示
        ///仍可作为封面参与合并 的本地化字符串。
        /// </summary>
        public static string CoverCannotDisplay {
            get {
                return ResourceManager.GetString("CoverCannotDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已从《{0}》中提取封面 的本地化字符串。
        /// </summary>
        public static string CoverExtracted {
            get {
                return ResourceManager.GetString("CoverExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面文件不存在
        ///请重新选择图片 的本地化字符串。
        /// </summary>
        public static string CoverFileMissing {
            get {
                return ResourceManager.GetString("CoverFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 《{0}》未包含有效封面图片 的本地化字符串。
        /// </summary>
        public static string CoverMissing {
            get {
                return ResourceManager.GetString("CoverMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面图片路径 的本地化字符串。
        /// </summary>
        public static string CoverPath {
            get {
                return ResourceManager.GetString("CoverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面预览 的本地化字符串。
        /// </summary>
        public static string CoverPreview {
            get {
                return ResourceManager.GetString("CoverPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件可能无法访问或封面格式不受支持 的本地化字符串。
        /// </summary>
        public static string CoverReadDetails {
            get {
                return ResourceManager.GetString("CoverReadDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从《{0}》读取封面：{1} 的本地化字符串。
        /// </summary>
        public static string CoverReadFailed {
            get {
                return ResourceManager.GetString("CoverReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将 EPUB 文件拖放到此处 的本地化字符串。
        /// </summary>
        public static string DropEpub {
            get {
                return ResourceManager.GetString("DropEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持拖放图片进行预览 的本地化字符串。
        /// </summary>
        public static string DropImageHint {
            get {
                return ResourceManager.GetString("DropImageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPUB 文件|*.epub|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string EpubFileFilter {
            get {
                return ResourceManager.GetString("EpubFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细错误日志已保存到：{0} 的本地化字符串。
        /// </summary>
        public static string ErrorLogSaved {
            get {
                return ResourceManager.GetString("ErrorLogSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以使用已有图书的封面 的本地化字符串。
        /// </summary>
        public static string ExistingCoverHint {
            get {
                return ResourceManager.GetString("ExistingCoverHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出封面图片 的本地化字符串。
        /// </summary>
        public static string ExportCover {
            get {
                return ResourceManager.GetString("ExportCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出封面图片 的本地化字符串。
        /// </summary>
        public static string ExportCoverImage {
            get {
                return ResourceManager.GetString("ExportCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 本 EPUB 的本地化字符串。
        /// </summary>
        public static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整路径 的本地化字符串。
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  GitHub 项目主页 的本地化字符串。
        /// </summary>
        public static string GithubHome {
            get {
                return ResourceManager.GetString("GithubHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史任务 的本地化字符串。
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件|*.jpg;*.jpeg;*.png;*.gif;*.webp;*.svg|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件|*{0}|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 EPUB 的本地化字符串。
        /// </summary>
        public static string InputEpub {
            get {
                return ResourceManager.GetString("InputEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载 {0} 图片 的本地化字符串。
        /// </summary>
        public static string LoadedImage {
            get {
                return ResourceManager.GetString("LoadedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在文件资源管理器中定位 的本地化字符串。
        /// </summary>
        public static string LocateInExplorer {
            get {
                return ResourceManager.GetString("LocateInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有合并任务正在运行 的本地化字符串。
        /// </summary>
        public static string MergeAlreadyRunning {
            get {
                return ResourceManager.GetString("MergeAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消合并 的本地化字符串。
        /// </summary>
        public static string MergeCanceled {
            get {
                return ResourceManager.GetString("MergeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并完成：{0} 的本地化字符串。
        /// </summary>
        public static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并完成 的本地化字符串。
        /// </summary>
        public static string MergeCompletedTitle {
            get {
                return ResourceManager.GetString("MergeCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已合并 {0}/{1} 本 EPUB 的本地化字符串。
        /// </summary>
        public static string MergedBooks {
            get {
                return ResourceManager.GetString("MergedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到需要合并的文件，请确认文件仍然存在且可以访问。 的本地化字符串。
        /// </summary>
        public static string MergeErrorFileNotFound {
            get {
                return ResourceManager.GetString("MergeErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并参数无效，请检查输入文件、输出位置和书名。 的本地化字符串。
        /// </summary>
        public static string MergeErrorInvalidArguments {
            get {
                return ResourceManager.GetString("MergeErrorInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPUB 文件结构无效或已损坏，请检查输入文件后重试。 的本地化字符串。
        /// </summary>
        public static string MergeErrorInvalidData {
            get {
                return ResourceManager.GetString("MergeErrorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件读写失败，请确认文件没有被其他程序占用，并检查磁盘空间。 的本地化字符串。
        /// </summary>
        public static string MergeErrorIo {
            get {
                return ResourceManager.GetString("MergeErrorIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 EPUB 包含暂不支持的内容，请更换文件后重试。 的本地化字符串。
        /// </summary>
        public static string MergeErrorNotSupported {
            get {
                return ResourceManager.GetString("MergeErrorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有权限读取输入文件或写入输出位置，请选择有权限的文件夹。 的本地化字符串。
        /// </summary>
        public static string MergeErrorUnauthorized {
            get {
                return ResourceManager.GetString("MergeErrorUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并失败，文件可能已损坏或格式不受支持。请检查输入文件后重试。 的本地化字符串。
        /// </summary>
        public static string MergeErrorUnknown {
            get {
                return ResourceManager.GetString("MergeErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPUB 内部目录格式无效，请更换文件后重试。 的本地化字符串。
        /// </summary>
        public static string MergeErrorXml {
            get {
                return ResourceManager.GetString("MergeErrorXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并失败 的本地化字符串。
        /// </summary>
        public static string MergeFailed {
            get {
                return ResourceManager.GetString("MergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并失败，请稍后重试。 的本地化字符串。
        /// </summary>
        public static string MergeFailedRetry {
            get {
                return ResourceManager.GetString("MergeFailedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并设置 的本地化字符串。
        /// </summary>
        public static string MergeSettings {
            get {
                return ResourceManager.GetString("MergeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并书名 的本地化字符串。
        /// </summary>
        public static string MergeTitle {
            get {
                return ResourceManager.GetString("MergeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在合并，请稍候… 的本地化字符串。
        /// </summary>
        public static string Merging {
            get {
                return ResourceManager.GetString("Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置底 的本地化字符串。
        /// </summary>
        public static string MoveBottom {
            get {
                return ResourceManager.GetString("MoveBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string MoveTop {
            get {
                return ResourceManager.GetString("MoveTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择封面图片 的本地化字符串。
        /// </summary>
        public static string NoCoverSelected {
            get {
                return ResourceManager.GetString("NoCoverSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未添加文件 的本地化字符串。
        /// </summary>
        public static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无历史任务 的本地化字符串。
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统没有找到可以打开 EPUB 文件的应用程序。请先安装或关联 EPUB 阅读器。 的本地化字符串。
        /// </summary>
        public static string OpenEpubFailed {
            get {
                return ResourceManager.GetString("OpenEpubFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件失败 的本地化字符串。
        /// </summary>
        public static string OpenFileFailed {
            get {
                return ResourceManager.GetString("OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击“是”打开文件，点击“否”打开所在文件夹。 的本地化字符串。
        /// </summary>
        public static string OpenOutputPrompt {
            get {
                return ResourceManager.GetString("OpenOutputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用默认应用打开 的本地化字符串。
        /// </summary>
        public static string OpenWithDefault {
            get {
                return ResourceManager.GetString("OpenWithDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出文件 的本地化字符串。
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取第 {0} 本 EPUB… 的本地化字符串。
        /// </summary>
        public static string ReadingBook {
            get {
                return ResourceManager.GetString("ReadingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选中项 的本地化字符串。
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已恢复历史任务配置 的本地化字符串。
        /// </summary>
        public static string RestoredTask {
            get {
                return ResourceManager.GetString("RestoredTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存合并后的 EPUB 的本地化字符串。
        /// </summary>
        public static string SaveMergedEpub {
            get {
                return ResourceManager.GetString("SaveMergedEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择封面图片 的本地化字符串。
        /// </summary>
        public static string SelectCoverImage {
            get {
                return ResourceManager.GetString("SelectCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 EPUB 文件 的本地化字符串。
        /// </summary>
        public static string SelectEpubFile {
            get {
                return ResourceManager.GetString("SelectEpubFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 EPUB 文件夹 的本地化字符串。
        /// </summary>
        public static string SelectEpubFolder {
            get {
                return ResourceManager.GetString("SelectEpubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要合并的 EPUB 文件 的本地化字符串。
        /// </summary>
        public static string SelectFilesToMerge {
            get {
                return ResourceManager.GetString("SelectFilesToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选择图片进行预览 的本地化字符串。
        /// </summary>
        public static string SelectImagePreview {
            get {
                return ResourceManager.GetString("SelectImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为此书封面 的本地化字符串。
        /// </summary>
        public static string SetCoverFromBook {
            get {
                return ResourceManager.GetString("SetCoverFromBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始合并 的本地化字符串。
        /// </summary>
        public static string StartMerge {
            get {
                return ResourceManager.GetString("StartMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按列表顺序合并；每本源书会成为合并目录的一级项目。 的本地化字符串。
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持 EPUB 2 / EPUB 3，封面支持 JPG、PNG、GIF、WEBP、SVG。 的本地化字符串。
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前格式无法使用系统解码器预览 的本地化字符串。
        /// </summary>
        public static string UnsupportedPreviewFormat {
            get {
                return ResourceManager.GetString("UnsupportedPreviewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPUB 合并工具 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
