//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpubMerge.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpubMerge.Gui.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 也可以使用下方按钮添加文件.
        /// </summary>
        public static string AddFilesHint {
            get {
                return ResourceManager.GetString("AddFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件夹.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：lanut | .
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在取消合并….
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法读取封面路径.
        /// </summary>
        public static string CannotReadCoverPath {
            get {
                return ResourceManager.GetString("CannotReadCoverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择封面.
        /// </summary>
        public static string ChooseCover {
            get {
                return ResourceManager.GetString("ChooseCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择位置.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此图片暂时无法展示
        ///仍可作为封面参与合并.
        /// </summary>
        public static string CoverCannotDisplay {
            get {
                return ResourceManager.GetString("CoverCannotDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已从《{0}》中提取封面.
        /// </summary>
        public static string CoverExtracted {
            get {
                return ResourceManager.GetString("CoverExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封面文件不存在
        ///请重新选择图片.
        /// </summary>
        public static string CoverFileMissing {
            get {
                return ResourceManager.GetString("CoverFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《{0}》未包含有效封面图片.
        /// </summary>
        public static string CoverMissing {
            get {
                return ResourceManager.GetString("CoverMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封面图片路径.
        /// </summary>
        public static string CoverPath {
            get {
                return ResourceManager.GetString("CoverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封面预览.
        /// </summary>
        public static string CoverPreview {
            get {
                return ResourceManager.GetString("CoverPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件可能无法访问或封面格式不受支持.
        /// </summary>
        public static string CoverReadDetails {
            get {
                return ResourceManager.GetString("CoverReadDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法从《{0}》读取封面：{1}.
        /// </summary>
        public static string CoverReadFailed {
            get {
                return ResourceManager.GetString("CoverReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将 EPUB 文件拖放到此处.
        /// </summary>
        public static string DropEpub {
            get {
                return ResourceManager.GetString("DropEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持拖放图片进行预览.
        /// </summary>
        public static string DropImageHint {
            get {
                return ResourceManager.GetString("DropImageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPUB 文件|*.epub|所有文件|*.*.
        /// </summary>
        public static string EpubFileFilter {
            get {
                return ResourceManager.GetString("EpubFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详细错误日志已保存到：{0}.
        /// </summary>
        public static string ErrorLogSaved {
            get {
                return ResourceManager.GetString("ErrorLogSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以使用已有图书的封面.
        /// </summary>
        public static string ExistingCoverHint {
            get {
                return ResourceManager.GetString("ExistingCoverHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出封面图片.
        /// </summary>
        public static string ExportCover {
            get {
                return ResourceManager.GetString("ExportCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出封面图片.
        /// </summary>
        public static string ExportCoverImage {
            get {
                return ResourceManager.GetString("ExportCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 本 EPUB.
        /// </summary>
        public static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完整路径.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  GitHub 项目主页.
        /// </summary>
        public static string GithubHome {
            get {
                return ResourceManager.GetString("GithubHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史任务.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片文件|*.jpg;*.jpeg;*.png;*.gif;*.webp;*.svg|所有文件|*.*.
        /// </summary>
        public static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片文件|*{0}|所有文件|*.*.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入 EPUB.
        /// </summary>
        public static string InputEpub {
            get {
                return ResourceManager.GetString("InputEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已加载 {0} 图片.
        /// </summary>
        public static string LoadedImage {
            get {
                return ResourceManager.GetString("LoadedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在文件资源管理器中定位.
        /// </summary>
        public static string LocateInExplorer {
            get {
                return ResourceManager.GetString("LocateInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已有合并任务正在运行.
        /// </summary>
        public static string MergeAlreadyRunning {
            get {
                return ResourceManager.GetString("MergeAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已取消合并.
        /// </summary>
        public static string MergeCanceled {
            get {
                return ResourceManager.GetString("MergeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并完成：{0}.
        /// </summary>
        public static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并完成.
        /// </summary>
        public static string MergeCompletedTitle {
            get {
                return ResourceManager.GetString("MergeCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已合并 {0}/{1} 本 EPUB.
        /// </summary>
        public static string MergedBooks {
            get {
                return ResourceManager.GetString("MergedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到需要合并的文件，请确认文件仍然存在且可以访问。.
        /// </summary>
        public static string MergeErrorFileNotFound {
            get {
                return ResourceManager.GetString("MergeErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并参数无效，请检查输入文件、输出位置和书名。.
        /// </summary>
        public static string MergeErrorInvalidArguments {
            get {
                return ResourceManager.GetString("MergeErrorInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPUB 文件结构无效或已损坏，请检查输入文件后重试。.
        /// </summary>
        public static string MergeErrorInvalidData {
            get {
                return ResourceManager.GetString("MergeErrorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件读写失败，请确认文件没有被其他程序占用，并检查磁盘空间。.
        /// </summary>
        public static string MergeErrorIo {
            get {
                return ResourceManager.GetString("MergeErrorIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前 EPUB 包含暂不支持的内容，请更换文件后重试。.
        /// </summary>
        public static string MergeErrorNotSupported {
            get {
                return ResourceManager.GetString("MergeErrorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有权限读取输入文件或写入输出位置，请选择有权限的文件夹。.
        /// </summary>
        public static string MergeErrorUnauthorized {
            get {
                return ResourceManager.GetString("MergeErrorUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并失败，文件可能已损坏或格式不受支持。请检查输入文件后重试。.
        /// </summary>
        public static string MergeErrorUnknown {
            get {
                return ResourceManager.GetString("MergeErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPUB 内部目录格式无效，请更换文件后重试。.
        /// </summary>
        public static string MergeErrorXml {
            get {
                return ResourceManager.GetString("MergeErrorXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并失败.
        /// </summary>
        public static string MergeFailed {
            get {
                return ResourceManager.GetString("MergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并失败，请稍后重试。.
        /// </summary>
        public static string MergeFailedRetry {
            get {
                return ResourceManager.GetString("MergeFailedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并设置.
        /// </summary>
        public static string MergeSettings {
            get {
                return ResourceManager.GetString("MergeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并书名.
        /// </summary>
        public static string MergeTitle {
            get {
                return ResourceManager.GetString("MergeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在合并，请稍候….
        /// </summary>
        public static string Merging {
            get {
                return ResourceManager.GetString("Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置底.
        /// </summary>
        public static string MoveBottom {
            get {
                return ResourceManager.GetString("MoveBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下移.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string MoveTop {
            get {
                return ResourceManager.GetString("MoveTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上移.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未选择封面图片.
        /// </summary>
        public static string NoCoverSelected {
            get {
                return ResourceManager.GetString("NoCoverSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还未添加文件.
        /// </summary>
        public static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无历史任务.
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统没有找到可以打开 EPUB 文件的应用程序。请先安装或关联 EPUB 阅读器。.
        /// </summary>
        public static string OpenEpubFailed {
            get {
                return ResourceManager.GetString("OpenEpubFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件失败.
        /// </summary>
        public static string OpenFileFailed {
            get {
                return ResourceManager.GetString("OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击“是”打开文件，点击“否”打开所在文件夹。.
        /// </summary>
        public static string OpenOutputPrompt {
            get {
                return ResourceManager.GetString("OpenOutputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用默认应用打开.
        /// </summary>
        public static string OpenWithDefault {
            get {
                return ResourceManager.GetString("OpenWithDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件.
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在读取第 {0} 本 EPUB….
        /// </summary>
        public static string ReadingBook {
            get {
                return ResourceManager.GetString("ReadingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除选中项.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已恢复历史任务配置.
        /// </summary>
        public static string RestoredTask {
            get {
                return ResourceManager.GetString("RestoredTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存合并后的 EPUB.
        /// </summary>
        public static string SaveMergedEpub {
            get {
                return ResourceManager.GetString("SaveMergedEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择封面图片.
        /// </summary>
        public static string SelectCoverImage {
            get {
                return ResourceManager.GetString("SelectCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 EPUB 文件.
        /// </summary>
        public static string SelectEpubFile {
            get {
                return ResourceManager.GetString("SelectEpubFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 EPUB 文件夹.
        /// </summary>
        public static string SelectEpubFolder {
            get {
                return ResourceManager.GetString("SelectEpubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要合并的 EPUB 文件.
        /// </summary>
        public static string SelectFilesToMerge {
            get {
                return ResourceManager.GetString("SelectFilesToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可选择图片进行预览.
        /// </summary>
        public static string SelectImagePreview {
            get {
                return ResourceManager.GetString("SelectImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设为此书封面.
        /// </summary>
        public static string SetCoverFromBook {
            get {
                return ResourceManager.GetString("SetCoverFromBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始合并.
        /// </summary>
        public static string StartMerge {
            get {
                return ResourceManager.GetString("StartMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按列表顺序合并；每本源书会成为合并目录的一级项目。.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持 EPUB 2 / EPUB 3，封面支持 JPG、PNG、GIF、WEBP、SVG。.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前格式无法使用系统解码器预览.
        /// </summary>
        public static string UnsupportedPreviewFormat {
            get {
                return ResourceManager.GetString("UnsupportedPreviewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPUB 合并工具.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
